# pull official base image
FROM node:alpine3.20 AS build

# set work directory
WORKDIR /usr/src/app/transcendence_front

RUN npm install -g @angular/cli@17.3.7
#copy entrypoint script
COPY ./entrypoint.prod.sh /tmp/entrypoint.sh

# ensure the entrypoint script is executable
RUN chmod +x /tmp/entrypoint.sh

# use entrypoint script
ENTRYPOINT ["/tmp/entrypoint.sh"]
