"""
Django settings for transcendence_back project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os
from datetime import timedelta
from corsheaders.defaults import default_headers

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

# 'DJANGO_ALLOWED_HOSTS' should be a single string of hosts with a space between each.
# For example: 'DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]'
#ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")
ALLOWED_HOSTS = ["*"]



# Application definition in alphabetical order

INSTALLED_APPS = [
    'daphne',
    'coreapi',
    'corsheaders',
    'django_celery_results',
    'django_channels.chat',
    'django_channels.game',
    'django_channels.tournament',
    'django_prometheus',
    'django_elasticsearch_dsl',
    'djoser',
    'pong_back',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pong_back.middleware.UpdateLastActivityMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'transcendence_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "transcendence_back.asgi.application"

# Channels
REDIS_HOST= os.environ.get("REDIS_HOST")
REDIS_PORT= os.environ.get("REDIS_PORT")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT, 0)],
        },
    },
}

WSGI_APPLICATION = 'transcendence_back.wsgi.application'

# Caché
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("POSTGRES_DB", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("POSTGRES_USER", "dev"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "transcendence"),
        "HOST": os.environ.get("POSTGRE_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRE_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'pong_back.validators.NumberValidator',
    },
    {
        'NAME': 'pong_back.validators.UppercaseValidator',
    },
    {
        'NAME': 'pong_back.validators.LowercaseValidator',
    },
    {
        'NAME': 'pong_back.validators.SymbolValidator',
    }
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'path_to_your_angular_app_static_files'),
# ]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-cors-headers config
# https://pypi.org/project/django-cors-headers/

# CORS_ALLOWED_ORIGINS = [
#      "https://localhost:8443",
#      "https://localhost",
#      "http://localhost:4200"
#  ]

# CORS_ALLOW_HEADERS = list(default_headers) + [
#     'forgot'
# ]

CSRF_TRUSTED_ORIGINS=[
    'https://localhost',
    'https://localhost:8443',
    'http://apacheback:8443'
]

# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^http://10\..*$",
#     r"^https://10\..*$"
# ]

# def generate_csrf_trusted_origins():
#     trusted_origins = [
#         'https://localhost',
#         'https://localhost:8443'
#     ]
#     # Agrega orígenes para la red 10.*
#     for i in range(256):
#         for j in range(256):
#             trusted_origins.append(f'http://10.{i}.{j}')
#     return trusted_origins

# CSRF_TRUSTED_ORIGINS = generate_csrf_trusted_origins()

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = '*'
CORS_ALLOW_METHODS = '*'

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^http://10\..*$",
#     r"^https://10\..*$"
# ]

# def generate_csrf_trusted_origins():
#     trusted_origins = [
#         'https://localhost',
#         'https://localhost:8443'
#     ]
#     # Agrega orígenes para la red 10.*
#     for i in range(256):
#         for j in range(256):
#             trusted_origins.append(f'http://10.{i}.{j}')
#     return trusted_origins

# CSRF_TRUSTED_ORIGINS = generate_csrf_trusted_origins()

# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_HEADERS = '*'
# CORS_ALLOW_METHODS = '*'

# CoreApi config
# https://www.django-rest-framework.org/community/3.10-announcement/

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASES": (
        'rest_framework.permissions.IsAuthenticated',
    )
}

AUTH_USER_MODEL = 'pong_back.Player'

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=3),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    'ALGORITHM': 'HS256',
        'SIGNING_KEY': os.environ.get("SECRET_KEY"),
        'VERIFYING_KEY': None,
        'AUDIENCE': None,
        'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'UPDATE_LAST_LOGIN': True,
}

DOMAIN = 'localhost:8280'
SITE_NAME = 'FT_TRANSCENDENCE'

# Email config
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND")
# MAILER_EMAIL_BACKEND= EMAIL_BACKEND
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# ACCOUNT_EMAIL_VERIFICATION = 'none'

ELASTICSEARCH_URL = os.environ.get("ELASTICSEARCH_URL")
ELASTICSEARCH_PASSWORD = os.environ.get("ELASTICSEARCH_PASSWORD")
ELASTICSEARCH_DEFAULT = os.environ.get("ELASTICSEARCH_DEFAULT")

ELASTICSEARCH_DSL={
    'default': {
        'hosts': f'http://{ELASTICSEARCH_DEFAULT}:{ELASTICSEARCH_PASSWORD}@{ELASTICSEARCH_URL}'
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(message)s %(asctime)s %(name)s %(lineno)d'
        },
    },
    'handlers': {
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'logstash': {
            'level': 'INFO',
            'class': 'logstash.TCPLogstashHandler',
            'host': 'logstash',
            'port': 5959,
            'version': 1,
            'message_type': 'django',
            'fqdn': False,
            'tags': ['django.request', 'django.channels.chat', 'django.channels.game', 'django.channels.tournament', 'pong_back'],
        },
    },
    'loggers': {
        'pong_back': {
            'handlers': ['console', 'logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.channels.chat': {
            'handlers': ['logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.contrib': {
            'handlers': ['logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'rest_framework': {
            'handlers': ['logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'corsheaders': {
            'handlers': ['logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'django_prometheus': {
            'handlers': ['logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    }
}

# CELERY
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/2'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_IMPORTS = ('pong_back.tasks',)

# MEDIA
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
